name: move_pull_request

on:
  pull_request:
    types: [ opened, closed ]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Testing automation
          column: Done
          repo-token: ${{ secrets.AUTOMATION }}
