#name: Link issue
#
#on:
#  issues:
#    types: [ opened ]
#
#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#jobs:
#  assign_one_project:
#    runs-on: ubuntu-latest
#    name: Assign to One Project
#    steps:
#      - name: Assign new issue to the project
#        uses: srggrs/assign-one-project-github-action@1.2.0
#        if: github.event.action == 'opened'
#        with:
#          project: https://github.com/SzymonJaworskiRF/github-actions-test/projects/1
#          column_name: To do
name: Assign issue

on:
  issues:
    types: [ opened ]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Testing automation
          column: To do
          repo-token: ${{ secrets.AUTOMATION }}
