name: Link issue

on:
  issues:
    types: [ opened ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign new issue to the project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: https://github.com/SzymonJaworskiRF/github-actions-test/projects/1
          column_name: To do
