name: GitHub projects automation

on:
  issues:
    types: [ opened, labeled ]
  pull_request:
    types: [ opened, labeled ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign new issues and new pull requests to a project
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/SzymonJaworskiRF/gh-pages-test/projects/1'
