name: Issue workflow

on:
  issues:
    types: [ opened, assigned, closed ]

jobs:
  move_issue_after_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'opened'
        with:
          project: Testing automation
          column: To do
          repo-token: ${{ secrets.AUTOMATION }}

  move_issue_after_assigned:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        if: github.event.action == 'assigned'
        with:
          project: Testing automation
          column: Ongoing
          repo-token: ${{ secrets.AUTOMATION }}

  move_issue_after_closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Testing automation
          column: Done
          repo-token: ${{ secrets.AUTOMATION }}
